apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-sequencer-delete-only
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
        - name: first-resource
          base:
            apiVersion: nop.crossplane.io/v1alpha1
            kind: NopResource
            spec:
              forProvider:
                conditionAfter:
                  - time: 5s
                    conditionType: Ready
                    conditionStatus: "True"
        - name: second-resource
          base:
            apiVersion: nop.crossplane.io/v1alpha1
            kind: NopResource
            spec:
              forProvider:
                conditionAfter:
                  - time: 5s
                    conditionType: Ready
                    conditionStatus: "True"
  - step: detect-readiness
    functionRef:
      name: function-auto-ready
  - step: sequence-deletion-only
    functionRef:
      name: function-sequencer
    input:
      apiVersion: sequencer.fn.crossplane.io/v1beta1
      kind: Input
      enableDeletionSequencing: true
      replayDeletion: true
      rules:
        - sequence:
          - first-resource
          - second-resource
          deleteOnly: true
